name: nasa-turbofan
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - tensorflow>=2.8.0
  - pip>=21.0.0
  - pip:
    - shap>=0.40.0
    - streamlit>=1.10.0
    - plotly>=5.6.0
    - tqdm>=4.64.0
    - pytest>=7.0.0
